/* Kide
 *
 * Copyright 2025 - 2026 Marko Salmela.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.fuusio.kide.devtools

/**
 * Turns a recorded [FlightRecorder] trace into a kotest regression-test scaffold.
 *
 * A bug reproduced once in a running app becomes a replayable test: the generator emits
 * the exact intent sequence and the recorded state transitions as assertions. Because
 * Kide's intent loop is lossless and reduces synchronous actions in dispatch order,
 * replaying the same intents against the same initial conditions is deterministic —
 * the recorded trace is a valid oracle.
 *
 * The scaffold marks intent construction sites with the recorded `toString()` renderings
 * and fully qualified class names; the developer (or an AI agent, which typically consumes
 * this via the `kide_export_regression_test` MCP tool and fills the literals in from
 * source) completes construction of intents and test doubles.
 */
public object TraceTestGenerator {

    /**
     * Generates a kotest `DescribeSpec` scaffold replaying the session recorded in [handle].
     */
    public fun generate(handle: DebugHandle): String {
        val events = handle.recorder.events
        val simpleName = handle.processorClassName.substringAfterLast('.')
        val builder = StringBuilder()

        builder.appendLine("// Generated by Kide DevTools from a recorded session of ${handle.processorClassName}.")
        builder.appendLine("// Regression-test scaffold: construct the processor with test doubles, then replay")
        builder.appendLine("// the recorded intents and assert the recorded state transitions.")
        builder.appendLine("//")
        builder.appendLine("// Recorded events: ${events.size} (session '${handle.name}')")
        builder.appendLine()
        builder.appendLine("class ${simpleName}ReplayTest : DescribeSpec({")
        builder.appendLine()
        builder.appendLine("    it(\"replays recorded session of $simpleName\") {")
        builder.appendLine("        val processor = TODO(\"construct ${handle.processorClassName} with test doubles\")")
        builder.appendLine()

        var step = 0
        for (event in events) {
            when (event.type) {
                TraceEventType.Intent -> {
                    step += 1
                    builder.appendLine("        // ── Step $step ────────────────────────────────────────────────")
                    builder.appendLine("        // processor.dispatch(<reconstruct ${event.payloadClass ?: "intent"}>)")
                    builder.appendLine("        //   recorded intent: ${event.payload}")
                }
                TraceEventType.StateChanged -> {
                    builder.appendLine("        //   expected state:  ${event.payload}")
                }
                TraceEventType.SideEffect -> {
                    builder.appendLine("        //   expected effect: ${event.payload}")
                }
                TraceEventType.Error -> {
                    builder.appendLine("        //   recorded ERROR:  ${event.payload}")
                }
                TraceEventType.ActionMapped, TraceEventType.ActionExecuting -> {
                    // Structural events; not needed in the replay scaffold.
                }
            }
        }

        val finalState = events.lastOrNull { it.type == TraceEventType.StateChanged }?.payload
        if (finalState != null) {
            builder.appendLine()
            builder.appendLine("        // Final assertion:")
            builder.appendLine("        // processor.state.toString() shouldBe")
            builder.appendLine("        //     \"${finalState.replace("\\", "\\\\").replace("\"", "\\\"")}\"")
        }

        builder.appendLine("    }")
        builder.appendLine("})")
        return builder.toString()
    }
}
