/* Kide
 *
 * Copyright 2025 - 2026 Marko Salmela.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.fuusio.kide.presentation

/**
 * A marker interface for intents specifying various user interaction events in the application's
 * presentation layer architecture.
 *
 * A [ViewIntent] represents any event generated by user interactions or system events in
 * the UI layer. The intents are received and handled by a [PresentationProcessor] that determines
 * what [Action] is mapped to be executed as a reaction to a received [ViewIntent].
 * 
 * Implementations of this interface should represent specific user interaction events such
 * as button clicks, form submissions, navigation requests, or any other user interaction that
 * requires processing. Each implementation should contain the necessary data associated with
 * the event.
 */
public interface ViewIntent : PresentationComponent